### ISSUE TITLE
When do you guys implement the "Upload to OneDrive"?

### ISSUE THREAD

**Issue by qinxgit** [OneDrive/onedrive-sample-apibrowser-dotnet#2]
When do you guys implement the "Upload to OneDrive" feature?

**Comment by qinxgit** [comment]
@cdmayer 

Looking at you guys' magic code that displayed a good file picker in a browser control, how can I do the similar thing to save a file?

```
            const string msaAuthUrl = "https://login.live.com/oauth20_authorize.srf";
            const string msaDesktopUrl = "https://login.live.com/oauth20_desktop.srf";
            string startUrl, completeUrl;

            var scopes = multiSelect ? "onedrive_onetime.access:readfile|multi" : "onedrive_onetime.access:readfile|single";

            Dictionary<string, string> urlParam = new Dictionary<string,string>();
            urlParam.Add(OAuthConstants.ClientIdKeyName, clientId);
            urlParam.Add(OAuthConstants.ScopeKeyName, scopes);
            urlParam.Add(OAuthConstants.RedirectUriKeyName, msaDesktopUrl);
            urlParam.Add(OAuthConstants.ResponseTypeKeyName, "token");

            startUrl = BuildUriWithParameters(msaAuthUrl, urlParam);
            completeUrl = msaDesktopUrl;

            FormOneDrivePicker authForm = new FormOneDrivePicker(startUrl, completeUrl);
            DialogResult result = await authForm.ShowDialogAsync(owner);
````

**Comment by cdmayer** [comment]
Take a look at `simpleUploadToolStripMenuItem_Click` in [FormBrowser.cs](https://github.com/OneDrive/onedrive-sample-apibrowser-dotnet/blob/master/OneDriveApiBrowser/FormBrowser.cs)

**Comment by qinxgit** [comment]
Why can't I find documentation for that?

**Comment by qinxgit** [comment]
Actually, what I am in need is some url based web view can do:
1) Let user choose a folder from oneDrive;
3) The API somehow return this folder address to my application.
So my application can upload a file to that folder. 

Thus I don't need to deal with the UI of how to display tiles for each folder, how the end-user interact with the UI. Just as you did in the file picker, your compose some url like
https://login.live.com/oauth20_desktop.srf?scope=onedrive_onetime.access:readfile|single&...., then OneDrive service automatically did the UI for us and just return what file has been picked. Is there an equivalent thing for choosing a folder? (No "Open" button, and can only select a folder)
